spring:
  application:
    name: academicsync

  datasource:
    url: jdbc:postgresql://localhost:5435/academicsync
    username: academicsync
    password: academicsync

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  rabbitmq:
    host: localhost
    port: 5672
    username: academicsync
    password: academicsync

server:
  port: 8080

academicsync:
  messaging:
      exchange: academicsync.events
      sync-routing-key: academicsync.sync.completed
      failure-routing-key: academicsync.sync.failed
  scheduler:
    enabled: true
    cron: "0 */15 * * * *"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: academicsync